In [1]:
import numpy as np

In [3]:
x = np.array([1.0,2.0,3.0])
y = np.array([2.0,4.0,6.0])

print(x + y)
print(x - y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[0.5 0.5 0.5]


In [5]:
x = np.array([1.0,2.0,3.0])
print(x / 2.0)

[0.5 1.  1.5]


In [7]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)
print(a.dtype) 

[[1 2]
 [3 4]]
(2, 2)
int64


In [8]:
b = np.array([[3,0],[0,6]])
print(a + b)
print(a * b)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


In [9]:
a = np.array([[1,2],[3,4]])
print(a)
print(a * 10)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


In [10]:
a = np.array([[1,2], [3,4]])
b = np.array([10,20])

print(a * b)

[[10 40]
 [30 80]]


In [14]:
x = np.array([[51,55],[14,19],[0,4]])
print(x)
print(x[0])

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
