## 배열 조회

In [1]:
def array_info(array) :
  print(array)
  print("ndim : ", array.ndim)
  print("shape : ", array.shape)
  print("dtype : ", array.dtype)
  print("size : ", array.size )
  print("itemsize : ", array.itemsize)
  print("nbytes : ", array.nbytes)
  print("strides : ", array.strides)

In [2]:
import numpy as np

a1 = np.array([1,2,3,4,5])

array_info(a1)

[1 2 3 4 5]
ndim :  1
shape :  (5,)
dtype :  int64
size :  5
itemsize :  8
nbytes :  40
strides :  (8,)


In [3]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim :  2
shape :  (3, 3)
dtype :  int64
size :  9
itemsize :  8
nbytes :  72
strides :  (24, 8)


In [4]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim :  3
shape :  (2, 3, 3)
dtype :  int64
size :  18
itemsize :  8
nbytes :  144
strides :  (72, 24, 8)


## 인덱싱

In [5]:
print(a1)
print(a1[0])
print(a1[1])
print(a1[-1])

[1 2 3 4 5]
1
2
5


In [6]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [7]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[1,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9


## 슬라이싱
- 슬라이싱 구분 : `a[start : stop : step]`
- 기본값 : `strat = 0` , `stop = ndim` , `step =1`

In [8]:
print(a1)
print(a1[:2])
print(a1[:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[1]
[1 3 5]
[5 4 3 2 1]


In [9]:
print(a2)
print('-'*40)
print(a2[1])
print('-'*40)
print(a2[1, :])
print('-'*40)
print(a2[:2, :2])
print('-'*40)
print(a2[1:, ::-1])
print('-'*40)
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
[4 5 6]
----------------------------------------
[4 5 6]
----------------------------------------
[[1 2]
 [4 5]]
----------------------------------------
[[6 5 4]
 [9 8 7]]
----------------------------------------
[[9 8 7]
 [6 5 4]
 [3 2 1]]


## 불리언 인덱싱
- 배열 각 요소의 선택 여부를 불리언으로 지정
- True 값인 인덱스의 값만 조회

In [10]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])

bi = [True,False,True,True,False]
print(a1[bi])

[1 2 3 4 5]
[2 3 5]
[1 3 4]


## 펜시 인덱싱

In [11]:
print(a1)
print(a1[0], a1[2])
print('*'*40)
ind = [0,2]
print(a1[ind])

[1 2 3 4 5]
1 3
****************************************
[1 3]


In [12]:
ind = np.array([[0,1], [2,0]])
print(a1[ind])

[[1 2]
 [3 1]]


In [17]:
print(a2)

row = np.array([0,2])
col = np.array([1,2])

print(a2[row,col])
print('*'*40)
print(a2[row, :])
print('*'*40)
print(a2[row,1])
print('*'*40)
print(a2[2,col])
print('*'*40)
print(a2[row,1:])
print('*'*40)
print(a2[1:,col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
****************************************
[[1 2 3]
 [7 8 9]]
****************************************
[2 8]
****************************************
[8 9]
****************************************
[[2 3]
 [8 9]]
****************************************
[[5 6]
 [8 9]]


# 배열 값 삽입 / 수정 / 삭제 / 복사

### 배열값 삽입
- `insert()` : 배열의 특정 위치에 값 삽입
- axis를 지정하지 않으면 1차원 배열로 변환
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [19]:
print(a1)
b1 = np.insert(a1,0,10) # a1의 0번 인덱스에 10 넣어 b1 배열 만들기
print(f'b1 : {b1}')
print(f'a1의 값은 바뀌지 않음 : {a1}')
c1 = np.insert(a1,2,10)
print(f'c1 : {c1}')


[1 2 3 4 5]
b1 : [10  1  2  3  4  5]
a1의 값은 바뀌지 않음 : [1 2 3 4 5]
c1 : [ 1  2 10  3  4  5]


In [21]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(f'{b2}')
print('*'*40)
c2 = np.insert(a2, 1, 10, axis=1)
print(f'{c2}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
****************************************
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

- 배열의 인덱싱으로 접근하여 값 수정

In [29]:
a1 = np.array([1,2,3,4,5])
print(a1)
a1[0] = 0
a1[1] = 1
a1[2] = 2
a1[3] = 3
a1[4] = 4
print(a1)
print('*'*40)

a1[:1] = 9
print(a1)
print('*'*40)

i = np.array([1,3,4])
a1[i] = 0
print(a1)
print('*'*40)

a1[i] += 4
print(a1)

[1 2 3 4 5]
[0 1 2 3 4]
****************************************
[9 1 2 3 4]
****************************************
[9 0 2 0 0]
****************************************
[9 4 2 4 4]


In [32]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[0] = 1
print(a2)
print('*'*40)
a2[1:,2] = 9
print(a2)
print('*'*40)
row = np.array([0,1])
col = np.array([1,2])
a2[row,col] = 0
print(a2)

[[1 1 1]
 [4 2 6]
 [7 8 3]]
****************************************
[[1 1 1]
 [4 2 9]
 [7 8 9]]
****************************************
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열값 삭제
- `delete()` : 배열의 특정 위치에 값을 삭제
- axis를 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [34]:
print(a1)
b1 = np.delete(a1,1)
print(b1)
print(a1)

[9 4 2 4 4]
[9 2 4 4]
[9 4 2 4 4]


In [36]:
print(a2)
print('*'*40)
b2 = np.delete(a2,1,axis=0)
print(b2)
print('*'*40)
c2 = np.delete(a2,1,axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
****************************************
[[1 0 1]
 [7 8 9]]
****************************************
[[1 1]
 [4 0]
 [7 9]]


### 배열 복사
- 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님
- 원본의 위치와 동일한 위치를 사용해서 원본 배열 또한 값이 바뀐다

In [39]:
print(a2)
print('*'*40)
print(a2[:2,:2])
print('*'*40)
a2_sub = a2[:2,:2]
print(a2_sub)
print('*'*40)
a2_sub[:, 1] = 0
print(a2_sub)
print('*'*40)
print(a2)


[[1 0 1]
 [4 2 0]
 [7 8 9]]
****************************************
[[1 0]
 [4 2]]
****************************************
[[1 0]
 [4 2]]
****************************************
[[1 0]
 [4 0]]
****************************************
[[1 0 1]
 [4 0 0]
 [7 8 9]]


- `copy()` : 배열이나 하위 배열 내의 값을 명시적으로 복사

In [41]:
print(a2)
print('*'*40)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print('*'*40)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
****************************************
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
****************************************
[[1 0 1]
 [4 0 0]
 [7 8 9]]


## 배열 변환

### 배열 전치 및 축 변경

In [51]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print('-'*30)
print(a2.T) # 행과 열이 바뀜

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [47]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
# print(a3.ndim)
print('-'*30)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
------------------------------
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [48]:
print(a2)
print('-'*30)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
------------------------------
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [49]:
print(a3)
print('-'*30)
print(a3.swapaxes(0,1))
print('-'*30)
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
------------------------------
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
------------------------------
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


## 배열 재구조화

- `reshape()` : 배열의 형상화를 변경

In [53]:
n1 = np.arange(1,10)
print(n1)
print('-'*30)
print(n1.reshape(3,3)) # 2차원으로만들기

[1 2 3 4 5 6 7 8 9]
------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- `newaxis()` : 새로운 축 추가

In [56]:
print(n1)
print('-'*30)
print(n1[np.newaxis, :5])
print('-'*30)
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
------------------------------
[[1 2 3 4 5]]
------------------------------
[[1]
 [2]
 [3]
 [4]
 [5]]


## 배열의 크기 변경

- 배열의 모양만 변경

In [67]:
import random

n2 = np.random.randint(0,10,(2,5))
print(n2)
print('-'*30)
n2.resize((5,2))
print(n2)

[[4 6 7 2 3]
 [9 6 3 1 3]]
------------------------------
[[4 6]
 [7 2]
 [3 9]
 [6 3]
 [1 3]]


- 배열 크기 증가
- 남은 공간은 0으로 채워줌

In [71]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
print('-'*30)
n2.resize((5, 5))
print(n2)

[[0 3 8 9 7]
 [5 3 8 4 3]]
------------------------------
[[0 3 8 9 7]
 [5 3 8 4 3]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- 배열의 크기 감소
- 포함되지 않은 값은 삭제됨

In [73]:
n2 = np.random.randint(0, 10, (2, 5))
n2.resize((3,3))
print(n2)

[[1 0 0]
 [6 3 0]
 [6 2 2]]


### 배열 추가

- `append()` : 배열의 끝에 값 추가

In [74]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('-'*30)
b2 = np.arange(10,19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[[10 11 12]
 [13 14 15]
 [16 17 18]]


- axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [75]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- axis를 0으로 지정
- shape[0]을 제외한 나머지 shape은 같아야 함

In [76]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


- axis를 1으로 지정
- shape[1]을 제외한 나머지 shape은 같아야 함

In [77]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

- `concatenate()` : 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [78]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [79]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [80]:
a2 = np.array([[1,2,3],[4,5,6]])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
a2 = np.array([[1,2,3],[4,5,6]])
np.concatenate([a2,a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- `vstack()` : 수직 스택, 1차원으로 연결

In [83]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- `hstack()` : 수평 스택, 2차원으로 연결

In [84]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- `dstack()` : 깊이 스택, 3차원으로 연결

In [85]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

- `stack()` : 새로운 차원으로 연결

In [86]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

- `slite()` : 배열 분할

In [88]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5]) # [5]는 기준이 되는 인덱스 위치
print(b1, c1)
print('-'*30)
b1,c1,d1,e1,f1 = np.split(a1, [2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
------------------------------
[0 1] [2 3] [4 5] [6 7] [8 9]


- `vsplit()` : 수직 분할, 1차원으로 분할

In [90]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('-'*30)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print('-'*30)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[[1 2 3]
 [4 5 6]]
------------------------------
[[7 8 9]]


- `hsplit()` : 수평 분할, 2차워능로 분할

In [91]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('-'*30)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print('-'*30)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[[1 2]
 [4 5]
 [7 8]]
------------------------------
[[3]
 [6]
 [9]]


- `dsplit()` : 깊이 분할, 3차원으로 분할

In [94]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
print('-'*30)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print('-'*30)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
------------------------------
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
------------------------------
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]
