## 배열 연산
- Numpy의 배열 연산은 벡터화 연산을 사용
- 일반적으로 Numpy의 범용 함수를 통해 구현
- 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드 캐스팅 (Broadcastin)
- NumPy에서 서로 다른 크기의 배열 간에 연산을 수행할 때 자동으로 배열의 모양을 맞춰주는 메커니즘
- 배열 연산은 같은 크기의 배열끼리만 가능하지만, 브로드캐스팅을 통해 크기가 다른 배열들도 연산할 수 있게 된다.

In [19]:
import numpy as np

a1 = np.array([1,2,3])
print(a1)
print('-'*40)
print(f'a1 + 5 = \n{a1+5}') # [6 7 8]
print('-'*40)

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('-'*40)
print(f'a1 + a2 = \n{a1+a2}')
print('-'*40)

b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print('-'*40)
print(f'a1 + b2 = \n{a1+b2}')

[1 2 3]
----------------------------------------
a1 + 5 = 
[6 7 8]
----------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
a1 + a2 = 
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
----------------------------------------
[[1]
 [2]
 [3]]
----------------------------------------
a1 + b2 = 
[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 산술 연산

| 연산자 | 범용 함수 | 설명 |
|:------:|:---------:|:----:|
|`+`|`np.app`|덧셈|
|`-`|`np.subtract`|뺄셈|
|`-`|`np.negative`|단항 음수|
|`*`|`np.multiply`|덧셈|
|`/`|`np.divide`|나눗셈|
|`//`|`np.floor_divide`|나눗셈 내림|
|`**`|`np.power`|지수 연산
|`%`|`np.mod`|나머지 연산|

In [24]:
a1 = np.arange(1, 10)
print(a1)
print('-'*40)
print(a1 + 1)
print('-'*40)
print(np.add(a1,10))
print('-'*40)
print(a1-2)
print('-'*40)
print(np.subtract(a1,10))
print('-'*40)
print(-a1)
print('-'*40)
print(np.negative(a1))
print('-'*40)
print(a1 * 2)
print('-'*40)
print(np.multiply(a1,2))
print('-'*40)
print(a1 / 2)
print('-'*40)
print(np.divide(a1,2))
print('-'*40)
print(a1 // 2)
print('-'*40)
print(np.floor_divide(a1,2)) # 내림
print('-'*40)
print(a1 ** 2)
print('-'*40)
print(np.power(a1,2))
print('-'*40)
print(a1 % 2)
print('-'*40)
print(np.mod(a1,2))

[1 2 3 4 5 6 7 8 9]
----------------------------------------
[ 2  3  4  5  6  7  8  9 10]
----------------------------------------
[11 12 13 14 15 16 17 18 19]
----------------------------------------
[-1  0  1  2  3  4  5  6  7]
----------------------------------------
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
----------------------------------------
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
----------------------------------------
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
----------------------------------------
[ 2  4  6  8 10 12 14 16 18]
----------------------------------------
[ 2  4  6  8 10 12 14 16 18]
----------------------------------------
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
----------------------------------------
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
----------------------------------------
[0 1 1 2 2 3 3 4 4]
----------------------------------------
[0 1 1 2 2 3 3 4 4]
----------------------------------------
[ 1  4  9 16 25 36 49 64 81]
----------------------------------------
[ 1  4  9 16 25 36 49 64 81]


In [26]:
import random

a1 = np.arange(1, 10)
print(a1)
print('-'*40)
b1 = np.random.randint(1,10,size=9) # size=9: 생성할 원소의 개수
print(b1)
print('-'*40)

print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
----------------------------------------
[2 3 5 2 5 4 7 4 5]
----------------------------------------
[ 3  5  8  6 10 10 14 12 14]
[-1 -1 -2  2  0  2  0  4  4]
[ 2  6 15  8 25 24 49 32 45]
[0.5        0.66666667 0.6        2.         1.         1.5
 1.         2.         1.8       ]
[0 0 0 2 1 1 1 2 1]
[     1      8    243     16   3125   1296 823543   4096  59049]
[1 2 3 0 0 2 0 0 4]


In [29]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print('-'*40)
b2 = np.random.randint(1, 10, size=(3,3)) # size=(3, 3) → 2차원 배열, 3행 3열
print(b2)
print('-'*40)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
[[7 9 8]
 [3 5 2]
 [3 8 1]]
----------------------------------------
[[ 8 11 11]
 [ 7 10  8]
 [10 16 10]]
[[-6 -7 -5]
 [ 1  0  4]
 [ 4  0  8]]
[[ 7 18 24]
 [12 25 12]
 [21 64  9]]
[[0.14285714 0.22222222 0.375     ]
 [1.33333333 1.         3.        ]
 [2.33333333 1.         9.        ]]
[[0 0 0]
 [1 1 3]
 [2 1 9]]
[[       1      512     6561]
 [      64     3125       36]
 [     343 16777216        9]]
[[1 2 3]
 [1 0 0]
 [1 0 0]]


## 절댓값 함수
- `absolute()`, `abs()` : 내장된 절대값 함수

In [31]:
a1 = np.random.randint(-10,10,size=5)
print(a1)
print('-'*40)
print(np.absolute(a1))
print('-'*40)
print(np.abs(a1))

[ -1  -3  -4  -2 -10]
----------------------------------------
[ 1  3  4  2 10]
----------------------------------------
[ 1  3  4  2 10]


## 제곱/제곱근 함수
- `square`, `sqrt` : 제곱, 제곱근 함수

In [32]:
print(a1)
print('-'*40)
print(np.square(a1))
print('-'*40)
print(np.sqrt(a1))

[ -1  -3  -4  -2 -10]
----------------------------------------
[  1   9  16   4 100]
----------------------------------------
[nan nan nan nan nan]


/tmp/ipython-input-32-3180808080.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


## 지수와 로그 함수

In [33]:
a1 = np.random.randint(1,10,size=5)
print(a1)
print('-'*40)
print(np.exp(a1))
print('-'*40)
print(np.exp2(a1))
print('-'*40)
print(np.power(a1,2))

[6 3 3 2 3]
----------------------------------------
[403.42879349  20.08553692  20.08553692   7.3890561   20.08553692]
----------------------------------------
[64.  8.  8.  4.  8.]
----------------------------------------
[36  9  9  4  9]


In [34]:
print(a1)
print('-'*40)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[6 3 3 2 3]
----------------------------------------
[1.79175947 1.09861229 1.09861229 0.69314718 1.09861229]
[2.5849625 1.5849625 1.5849625 1.        1.5849625]
[0.77815125 0.47712125 0.47712125 0.30103    0.47712125]


## 삼각함수

| 함수 | 설명 |
|:----:|:----:|
|np.sin(array) | 요소 별 사인|
|np.cos(array) | 요소 별 코사인|
|np.tan(array) | 요소 별 탄젠트|
|np.arcsin(array) | 요소 별 아크 사인|
|np.arccos(array) | 요소 별 아크 코사인|
|np.arctan(array) | 요소 별 아크 탄젠트|

In [35]:
t = np.linspace(0, np.pi, 3)
print(t)
print('-'*40)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
----------------------------------------
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [36]:
x = [-1, 0, 1]
print(x)
print('-'*40)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
----------------------------------------
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


## 집계 함수

- `sum()` : 합 계산

In [ ]:
a2 = np.random.randint(1,10,size=(3,3))