# PyTorch
- 과학 연산을 위한 라이브러리
- <b>GPU</b>를 이용한 텐서 조작 및 동적 신경망 구축이 가능하도록 딥러닝 프레임워크를 발전 시킴

## 텐서
- 데이터 표현을 위한 기본 구조
- 데이터를 담기 위한 컨테이너로서 일반적으로 수치형 데이터를 저장
- 넘파이의 ndarray와 유사 (다차원 행렬과 유사)
- GPU를 사용한 연산 가속 가능

In [1]:
import torch

torch.__version__

'2.6.0+cu124'

In [2]:
# 초기화 되지 않은 텐서

x = torch.empty(4, 2)
print(x)

tensor([[0.0000e+00, 4.5101e-41],
        [1.8788e+31, 1.7220e+22],
        [2.1715e-18, 6.6471e+22],
        [5.3691e-05, 2.6853e-06]])


In [3]:
# 무작위로 초기화 된 텐서

x = torch.rand(4, 2)
print(x)

tensor([[0.0930, 0.4634],
        [0.8255, 0.8517],
        [0.2164, 0.3811],
        [0.4472, 0.3748]])


In [4]:
# 데이터 타입이 long이고 , 0으로 채워진 텐서

x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [5]:
# 사용자가 입력한 값으로 텐서 초기화

x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [6]:
# 2 x 4 크기, double 타입 1로 채워진 텐서

x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [7]:
# 같은 크기, float 타입, 무작위로 채워진 텐서

x = torch.randn_like(x, dtype=float)
print(x)

tensor([[-0.7602,  0.1969,  0.1405,  0.4477],
        [-0.6898, -1.3753, -1.4672,  0.4503]], dtype=torch.float64)


In [8]:
# 텐서의 크기 계산

print(x.size())

torch.Size([2, 4])


In [9]:
# 데이터 타입

ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [11]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [13]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [14]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


## CUDA Tensor
- `.to` 메소드를 통해 텐서를 어떠한 장치 (cpu, gpu) 로도 옮길 수 있음

In [15]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.7466])
-0.7465894818305969
torch.float32


In [19]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'현재의 디바이스 : {device}')
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))
print(z)

현재의 디바이스 : cuda
tensor([1.], device='cuda:0')
tensor([-0.7466], device='cuda:0')
tensor([0.2534], device='cuda:0')
tensor([0.2534], dtype=torch.float64)
tensor([0.2534], device='cuda:0')


## 다차원 텐서 표현

In [21]:
# 0D Tensor
# 하나의 숫자를 담고 있는 탠서
# 축과 형상이 없음

t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [22]:
# 1D Tensor (Vector)
# 값들을 저장한 리스트와 유사한 텐서
# 하나의 축이 존재

t1 = torch.tensor([1,2,3])
print(t1.ndim) # 차원
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [24]:
# 2D Tensor (Matrix)
# 행렬과 같은 모양으로 두개의 축이 존재
# 일반적인 수치, 통계 데이터셋이 해당
# 주로 샘플(Samples)과 특성(Features)을가진 구조로 사용

t2 = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(t2.ndim) # 차원
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [25]:
# 3D Tensor
# 큐브(cube)와 같은 모양으로 세개의 축이 존재
# 데이터가 연속된 시퀀스 데이터나 시가 축이 포함된 시계열 데이터에 해당
# 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등이 존재
# 주로 샘플(Samples), 타임스템(Timesteps), 특성(Features)을 가진 구조로 사용

t3 = torch.tensor([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                   [[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                   [[1,2,3],
                  [4,5,6],
                  [7,8,9]]])
print(t3.ndim) # 차원
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [28]:
# 4D Tensor
# 4개의 축
# 컬러 이미지 데이터가 대표적인 사례 (흑백 이미지 데이터는 3D Tensor로 가능)
# 주로 샘플(samples), 높이(height), 너비(width), 컬러 채널(channel)을 가진 구조로 사용

t4 = torch.tensor([[[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]],
                  [[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]]])
print(t4.ndim)
print(t4.shape)
print(t4)

4
torch.Size([2, 2, 3, 3])
tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])


In [29]:
# 5D Tensor
# 5개의 축
# 비디오데이터가 대표적인 사례
# 주로 샘플(samples), 프레임(Frames), 높이(height), 너비(width), 컬러 채널(channel)을 가진 구조로 사용

t5 = torch.tensor([[[[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]],
                  [[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]]],
                  [[[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]],
                  [[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]]]])
print(t5.ndim)
print(t5.shape)
print(t5)

5
torch.Size([2, 2, 2, 3, 3])
tensor([[[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],


         [[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]],



        [[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],


         [[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]])


In [32]:
# 텐서의 연산
# 텐서에 대한 수학연산, 삼각함수, 비트연산, 비교 연산, 집계 등 제공

import math

a = torch.rand(1,2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[0.5582, 0.8293]])
tensor([[0.5582, 0.8293]])
tensor([[1., 1.]])
tensor([[0., 0.]])
tensor([[0.5000, 0.5000]])
