# PyTorch
- 과학 연산을 위한 라이브러리
- <b>GPU</b>를 이용한 텐서 조작 및 동적 신경망 구축이 가능하도록 딥러닝 프레임워크를 발전 시킴

## 텐서
- 데이터 표현을 위한 기본 구조
- 데이터를 담기 위한 컨테이너로서 일반적으로 수치형 데이터를 저장
- 넘파이의 ndarray와 유사 (다차원 행렬과 유사)
- GPU를 사용한 연산 가속 가능

In [ ]:
import torch

torch.__version__

'2.6.0+cu124'

In [ ]:
# 초기화 되지 않은 텐서

x = torch.empty(4, 2)
print(x)

tensor([[-5.8393e+02,  4.3992e-41],
        [-5.8395e+02,  4.3992e-41],
        [-5.8639e+02,  4.3992e-41],
        [-5.8643e+02,  4.3992e-41]])


In [ ]:
# 무작위로 초기화 된 텐서

x = torch.rand(4, 2)
print(x)

tensor([[0.7223, 0.5290],
        [0.0290, 0.4108],
        [0.9690, 0.5624],
        [0.8044, 0.4205]])


In [ ]:
# 데이터 타입이 long이고 , 0으로 채워진 텐서

x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [ ]:
# 사용자가 입력한 값으로 텐서 초기화

x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [ ]:
# 2 x 4 크기, double 타입 1로 채워진 텐서

x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [ ]:
# 같은 크기, float 타입, 무작위로 채워진 텐서

x = torch.randn_like(x, dtype=float)
print(x)

tensor([[-0.3041,  0.1017,  0.3352,  0.3874],
        [ 2.6053, -0.0937, -2.3188, -0.7400]], dtype=torch.float64)


In [ ]:
# 텐서의 크기 계산

print(x.size())

torch.Size([2, 4])


In [ ]:
# 데이터 타입

ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [ ]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [ ]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [ ]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


## CUDA Tensor
- `.to` 메소드를 통해 텐서를 어떠한 장치 (cpu, gpu) 로도 옮길 수 있음

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.5679])
0.5679059028625488
torch.float32


In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'현재의 디바이스 : {device}')
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))
print(z)

현재의 디바이스 : cuda
tensor([1.], device='cuda:0')
tensor([0.5679], device='cuda:0')
tensor([1.5679], device='cuda:0')
tensor([1.5679], dtype=torch.float64)
tensor([1.5679], device='cuda:0')


## 다차원 텐서 표현

In [ ]:
# 0D Tensor
# 하나의 숫자를 담고 있는 탠서
# 축과 형상이 없음

t0 = torch.tensor(0)
print(t0.ndim) # 차원 수
print(t0.shape)
print(t0.size())
print(t0.item())
print(t0)

0
torch.Size([])
torch.Size([])
0
tensor(0)


In [ ]:
# 1D Tensor (Vector)
# 값들을 저장한 리스트와 유사한 텐서
# 하나의 축이 존재

t1 = torch.tensor([1,2,3])
print(t1.ndim) # 차원
print(t1.shape)
print(t1.size())
print(t1.numel())
print(t1[0])
print(t1[1])
print(t1)

1
torch.Size([3])
torch.Size([3])
3
tensor(1)
tensor(2)
tensor([1, 2, 3])


In [ ]:
# 2D Tensor (Matrix)
# 행렬과 같은 모양으로 두개의 축이 존재
# 일반적인 수치, 통계 데이터셋이 해당
# 주로 샘플(Samples)과 특성(Features)을가진 구조로 사용

t2 = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(t2.ndim) # 차원
print(t2.shape)
print(t2.size())
print(t2.numel())
print(t2[0])
print(t2[1])
print(t2[0][1])
print(t2[1,2])
print(t2)

2
torch.Size([3, 3])
torch.Size([3, 3])
9
tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(2)
tensor(6)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
# 3D Tensor
# 큐브(cube)와 같은 모양으로 세개의 축이 존재
# 데이터가 연속된 시퀀스 데이터나 시가 축이 포함된 시계열 데이터에 해당
# 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등이 존재
# 주로 샘플(Samples), 타임스템(Timesteps), 특성(Features)을 가진 구조로 사용

t3 = torch.tensor([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                   [[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                   [[1,2,3],
                  [4,5,6],
                  [7,8,9]]])
print(t3.ndim) # 차원
print(t3.shape)
print(t3.size())
print(t3.numel())
print(t3[1])
print(t3[1,2])
print(t3[1,2,0])
print(t3)

3
torch.Size([3, 3, 3])
torch.Size([3, 3, 3])
27
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([7, 8, 9])
tensor(7)
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
# 4D Tensor
# 4개의 축
# 컬러 이미지 데이터가 대표적인 사례 (흑백 이미지 데이터는 3D Tensor로 가능)
# 주로 샘플(samples), 높이(height), 너비(width), 컬러 채널(channel)을 가진 구조로 사용

t4 = torch.tensor([[[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]],
                  [[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]]])
print(t4.ndim)
print(t4.shape)
print(t4.size())
print(t4.numel())
print(t4[0])
print(t4[0,1])
print(t4)

4
torch.Size([2, 2, 3, 3])
torch.Size([2, 2, 3, 3])
36
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])


In [ ]:
# 5D Tensor
# 5개의 축
# 비디오데이터가 대표적인 사례
# 주로 샘플(samples), 프레임(Frames), 높이(height), 너비(width), 컬러 채널(channel)을 가진 구조로 사용

t5 = torch.tensor([[[[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]],
                  [[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]]],
                  [[[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]],
                  [[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]]]]])
print(t5.ndim)
print(t5.shape)
print(t5.size())
print(t5.numel())
print(t5)

5
torch.Size([2, 2, 2, 3, 3])
torch.Size([2, 2, 2, 3, 3])
72
tensor([[[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],


         [[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]],



        [[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],


         [[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]])


In [ ]:
# 텐서의 연산
# 텐서에 대한 수학연산, 삼각함수, 비트연산, 비교 연산, 집계 등 제공

import math

a = torch.rand(1,2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[-0.7353,  0.9194]])
tensor([[0.7353, 0.9194]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.5000,  0.5000]])


In [ ]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,2])))

tensor([[-0.7353,  0.9194]])
tensor(-0.7353)
tensor(0.9194)
tensor(0.0921)
tensor(1.1700)
tensor(-0.6760)
tensor([1, 2, 3])


In [ ]:
# 텐서 연산 연습 1

a = torch.tensor([1,2]) * 2 - 1
print(a)
print(torch.abs(a)) # 절댓값
print(torch.ceil(a)) # 반올림
print(torch.floor(a)) # 내림
print(torch.clamp(a, -0.5, 0.5))

tensor([1, 3])
tensor([1, 3])
tensor([1, 3])
tensor([1, 3])
tensor([0.5000, 0.5000])


In [ ]:
# 텐서 연산 연습 2

a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

result = a + b
print(result)

result = a - b
print(result)

result = a * b
print(result)

result = a / b
print(result)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [ ]:
# 행렬 연산

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

# 행렬 덧셈
print(a + b)

# 행렬 뺄셈
print(a - b)

# 행렬 곱셈
print(torch.matmul(a,b))

# 행렬 나눗셈
print(a / b)

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[19, 22],
        [43, 50]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
